## Задача 2 - Обработка и выборка данных

В этой проблеме вы почистите данные из нашего файла данных, удалив значения без дат, преобразовав значения температуры из Фаренгейта в Цельсии и разложите данные на отдельные наборы, используя код идентификации метеостанции. Мы начнем с очистки и преобразования наших температурных данных. Пожалуйста, выполните задачи ниже, записав свой код в кодовые ячейки в каждом разделе.

### Советы по выполнению упражнения

- Используйте **в точности** те же имена переменных, что и в инструкциях, потому что ваши ответы будут автоматически оценены, и тесты, которые оценивают ваши ответы, зависят от того же форматирования или именования переменных, что и в инструкциях.

- **Пожалуйста**,

    - **Не изменяйте имена файлов**. Сделайте всю работу в файле `Exercise-5-problem-2.ipynb` (этом файле).
    - **Не копируйте/вставляйте ячейки в этом блокноте**. Мы используем автоматизированную систему оценки, которая не будет работать, если есть копии кодовых ячеек.
    - **Не изменяйте типы ячеек**. Вы можете добавить ячейки, но изменение типов ячеек для существующих ячеек (например, c кода на Markdown) также приведет к выходу из строя автоматизированной проверки.

### Условия успешного выполнения задания

- Создание нового объетка DataFrame под названием `selected`, который содержит выбраееые столбцы
- Очистка набора данных путем удаления значений без данных
- Создание новой колонки для температуры, преобразованной из Фаренгейта в Цельсии
- Разделение данных на отдельные наборы для станций Helsinki Kumpula и Rovaniemi
- Сохранение в файлы CSV
- Добавление комментарии, которые объясняют, что делают большинство строк в коде
- Ответы на пару вопросов в конце задания
- Загрузка вашего блокнота в репозиторий 

## Соглашение об использовании ИИ

**Введите свое имя в ячейку ниже** чтобы подтвердить, что вы следовали [принципам курса об использовании инструментов ИИ](https://geo-python-2024.readthedocs.io/ru/latest/course-info/ai-tools.html) и понимаете, что использование инструментов ИИ считается обманом.

Павел Федоров

### Часть 1

Первый шаг для этой задачи - загрузить файл данных `6153237444115dat.csv` еще раз в переменную `data` с помощью pandas. Не забудьте указать значения без данных (вы можете скопировать свой код из задачи 1).

In [22]:
import pandas as pd # импортировал пандас

In [23]:
data = None

data = pd.read_csv(
    '6153237444115dat.csv', na_values=['*', '**', '***', '****', '*****', '******']
) # загрузил файл в пандас, na_values использовал чтобы пандас понял, что звездочки - это именно отсутсвиее данных, а не что-то еще

Убедитесь, что первые ряды DataFrame выглядят хорошо:

In [24]:
data.head()

USAF   WBAN  YR--MODAHRMN    DIR   SPD   GUS  CLG  SKC   L   M  ...  \
0  28450  99999  201705010000  174.0  10.0  14.0  NaN  NaN NaN NaN  ...   
1  28450  99999  201705010020  180.0  10.0   NaN  4.0  NaN NaN NaN  ...   
2  28450  99999  201705010050  190.0  10.0   NaN  4.0  NaN NaN NaN  ...   
3  28450  99999  201705010100  188.0  12.0  16.0  NaN  NaN NaN NaN  ...   
4  28450  99999  201705010120  200.0  13.0   NaN  2.0  OBS NaN NaN  ...   

      SLP    ALT    STP  MAX  MIN  PCP01  PCP06  PCP24  PCPXX    SD  
0  1009.2    NaN  984.1  NaN  NaN    NaN    NaN    NaN    NaN  35.0  
1     NaN  29.74    NaN  NaN  NaN    NaN    NaN    NaN    NaN   NaN  
2     NaN  29.74    NaN  NaN  NaN    NaN    NaN    NaN    NaN   NaN  
3  1009.1    NaN  984.0  NaN  NaN    NaN    NaN    NaN    NaN  35.0  
4     NaN  29.74    NaN  NaN  NaN    NaN    NaN    NaN    NaN   NaN  

[5 rows x 33 columns]

Проверьте количество строк в DataFrame:

In [25]:
print(len(data))

11694


### Часть 2

Далее, ваша задача состоит в том, чтобы получить поднабор данных, удалив строки с отсутствующими значениями температуры.

- Выберите колонки `USAF`, `YR--MODAHRMN`, `TEMP`, `MAX`, и `MIN` из `data` и поместите их в переменную `selected`
- Удалите все строки из `selected` которые не имеют данных в колонке `TEMP` с помощью функции `dropna()` 

In [26]:
selected = None

selected = data.loc[0:11694, ['USAF','YR--MODAHRMN','TEMP','MAX','MIN']]
selected = selected.dropna(subset = ['TEMP']) #удалил все строчки TEMP, где нет данных

Убедитесь, что вы выбрали правильные имена столбцов:

In [27]:
selected.head()

USAF  YR--MODAHRMN  TEMP  MAX  MIN
0  28450  201705010000  31.0  NaN  NaN
1  28450  201705010020  30.0  NaN  NaN
2  28450  201705010050  30.0  NaN  NaN
3  28450  201705010100  31.0  NaN  NaN
4  28450  201705010120  30.0  NaN  NaN

Проверьте, сколько у вас строк после удаления значений без данных:

In [28]:
len(selected)

11691

### Часть 3 

Затем вы можете преобразовать значения температуры из Фаренгейта в Цельсии.

- Создайте новый столбец в `selected` с именем `Celsius`
- Преобразуйте температуру в Фаренгейтах из `TEMP` используя формулу преобразования ниже и сохраните результаты в новой колонке `Celsius`.

$$
\Large
\begin{equation}
  T_{\mathrm{Celsius}} = (T_{\mathrm{Fahrenheit}} - 32)~/~1.8
\end{equation}
$$

- Округлите значение в колонке `Celsius` до 0 знаков после запятой (**не** создавайте новую колонку, обновите текущую)
- Преобразуйте значения `Celsius` в целочисленные (**не** создавайте новую колонку, обновите текущую)

In [29]:
selected.round(2) # Это нужно для задания в конце - округлить все данные до 2 десятичных значения для данных с плавающей запятой

USAF  YR--MODAHRMN  TEMP  MAX  MIN
0      28450  201705010000  31.0  NaN  NaN
1      28450  201705010020  30.0  NaN  NaN
2      28450  201705010050  30.0  NaN  NaN
3      28450  201705010100  31.0  NaN  NaN
4      28450  201705010120  30.0  NaN  NaN
...      ...           ...   ...  ...  ...
11689  29980  201708311900  64.0  NaN  NaN
11690  29980  201708312000  64.0  NaN  NaN
11691  29980  201708312100  64.0  NaN  NaN
11692  29980  201708312200  64.0  NaN  NaN
11693  29980  201708312300  64.0  NaN  NaN

[11691 rows x 5 columns]

In [30]:
selected['Celsius'] = 0.0 # создал столбец Celsius
for idx, row in selected.iterrows():
    TEMP_C = (row['TEMP'] - 32)/1.8 # для каждой строчки в столбце TEMP перевел данные из фаренгейта в цельсий
    selected.at[idx, 'Celsius'] = TEMP_C # добавил значения цельсия в пустой пока что столбец Celsius
selected.Celsius = selected.Celsius.round() # округлил зачения в Celsius
selected.Celsius = selected.Celsius.astype(int) # преобразовал значения в целочисленные

In [31]:
# проверьте данные
selected.head()

USAF  YR--MODAHRMN  TEMP  MAX  MIN  Celsius
0  28450  201705010000  31.0  NaN  NaN       -1
1  28450  201705010020  30.0  NaN  NaN       -1
2  28450  201705010050  30.0  NaN  NaN       -1
3  28450  201705010100  31.0  NaN  NaN       -1
4  28450  201705010120  30.0  NaN  NaN       -1

In [32]:
# проверьте типы данных
print(selected.dtypes)

USAF              int64
YR--MODAHRMN      int64
TEMP            float64
MAX             float64
MIN             float64
Celsius           int64
dtype: object


### Часть 4 

Ваша следующая задача - разделить `selected` на два отдельных набора данных. Пожалуйста, используйте заданные имена переменных и напишите свой ответ в ячейке ниже.

- Выберите все ряды в `selected` (объект DataFrame) со значением кода станции `USAF` равным `29980` и сохранитей их в переменной `kumpula`
- Выберите все ряды в `selected` (объект DataFrame) со значением кода станции `USAF` равным `28450` и сохранитей их в переменной `rovaniemi`

In [33]:
kumpula = None
rovaniemi = None

kumpula = selected[selected['USAF'] == 29980] # добавил в kumpula все значения selected, в которых USAF равен 29980
rovaniemi = selected[selected['USAF'] == 28450] # добавил в rovaniemi все значения selected, в которых USAF равен 28450

In [34]:
# проверьте данные
print(f"Kumpula: \n{kumpula.head()}\n")

Kumpula: 
       USAF  YR--MODAHRMN  TEMP  MAX  MIN  Celsius
8770  29980  201705010000  37.0  NaN  NaN        3
8771  29980  201705010100  37.0  NaN  NaN        3
8772  29980  201705010200  37.0  NaN  NaN        3
8773  29980  201705010300  37.0  NaN  NaN        3
8774  29980  201705010400  39.0  NaN  NaN        4



In [35]:
# проверьте данные
print(f"Rovaniemi: \n{rovaniemi.head()}\n")

Rovaniemi: 
    USAF  YR--MODAHRMN  TEMP  MAX  MIN  Celsius
0  28450  201705010000  31.0  NaN  NaN       -1
1  28450  201705010020  30.0  NaN  NaN       -1
2  28450  201705010050  30.0  NaN  NaN       -1
3  28450  201705010100  31.0  NaN  NaN       -1
4  28450  201705010120  30.0  NaN  NaN       -1



### Часть 5

Сохраним получившиеся выборки в файл.

- Сохраните `kumpula` (объект DataFrame) в файл `Kumpula_temps_May_Aug_2017.csv` (формат CSV)
- Сохраните `rovaniemi` (объект DataFrame) в файл `Rovaniemi_temps_May_Aug_2017.csv` (формат CSV)

Для каждого файла обязательно

- Используйте разделитель "запятая" (`,`)
- Используйте только 2 десятичных значения для данных с плавающей запятой

Не забудьте сохранить оба файла данных в вашем репозитории упражнения 5!

In [36]:
kumpula.to_csv("Kumpula_temps_May_Aug_2017.csv",
              sep = ',') # использовал разделитель, т.е. запятую
rovaniemi.to_csv("Rovaniemi_temps_May_Aug_2017.csv",
                sep = ',') # тоже самое, что и с kumpula

In [37]:
#Ячейка только для чтения для скрытых тестов :)

### Подитог 

- Было ли вам что-нибудь непонятно в ходе выполнения этой задачи?
- Вы столкнулись с какими-либо проблемами с десятичным форматированием?

Кроме того, убедитесь:

- Убедитесь, что ваш код включает информативные комментарии, объясняющие, что делает ваш код
- Опубликуйте свои изменения в репозиторий для упражнения 5 (включая 2 новых файла данных)

Пожалуйста, напишите свои ответы и комментарии ниже (**активируйте ячейку двойным щелчком**).

Все понятно, спасибо

### К задаче 3

Теперь вы можете перейти к [Задаче 3: Анализ данных](Exercise-5-problem-3.ipynb)